### ISSUE TITLE
KConMapperProperty issue when using fromClasses

### ISSUE THREAD

**Issue by SamihMustafa** [YanneckReiss/KConMapper#3]
Hi I am currently facing an issue with generating the right Mapper with the models I have. Please see below. It generates correctly for TestRepo.toTestRemote() but doesn't for TestRemote.toTestRepo. I currently can't move the kConMapper to TestRemote as it lives in another module and doesn't have access to TestRepo. 

Test classes: 
```
data class TestRemote(
    val uid: String,
    val name: String
)

@KConMapper(fromClasses = [TestRemote::class], toClasses = [TestRemote::class])
data class TestRepo(
    @KConMapperProperty(["uid"])
    val userUid: String,
    @KConMapperProperty(["name"])
    val fullName: String
)
```

which generates

```
fun TestRemote.toTestRepo(
   userUid: String,
   name: String
) = TestRepo(
   userUid = userUid,
   name = name
)

fun TestRepo.toTestRemote() = TestRemote(
   uid = this.userUid,
   fullName = this.name,
)
```

**Comment by YanneckReiss** [comment]
Could you please verify if the bug still exists in your project with KConMapper version `1.0.0-alpha04`?

**Comment by SamihMustafa** [comment]
still exists, doesn't map the propertyName for TestRemote.toTestRepo()
